### ISSUE TITLE
`/omp remove` does not remove directory plugins

### ISSUE THREAD

**Issue by NhanAZ** [thebigcrafter/oh-my-pmmp#16]
## Describe the bug
- Expected result: The `ExamplePlugin` plugin file will be deleted
- Actual result: No response received

## Steps to reproduce the issue
1. `/omp install ExamplePlugin latest true`
2. `/omp remove ExamplePlugin`

## OS and versions
 - PocketMine: [4.6.0]
 - PHP: [8.0.19]
 - Server OS: [Windows]

**Comment by tobydev27** [comment]
Solved by https://github.com/thebigcrafter/oh-my-pmmp/commit/6b9436d5b721e2c00e88bfc4dbf73a04c992edb0
