### ISSUE TITLE
The `#2` argument of `/omp install` should have a default value

### ISSUE THREAD

**Issue by NhanAZ** [thebigcrafter/oh-my-pmmp#20]
The `#2` argument of `/omp install` should have a default value

Expect: `/omp install Track`
If argument `#2` is not passed, `latest` will be used instead

\* This issue may give rise to a different problem than the question: What if I want to download the plugin as a file but I don't want to import the plugin version?
The command I want to use in the above case is: `/omp install Track true`

---

Please consider and close this issue if it is not possible

**Comment by NhanAZ** [comment]
`/omp update` should also have a default version value of "latest"

**Comment by Phuongaz** [comment]
Why do you want to use `/omp install Track true` instead of that? They can input `/omp install Track latest true` if they want to download as a file?, that makes you try to change the position of the arguments.
