### ISSUE TITLE
Error: "Argument #1 ($pluginsList) must be of type array, null given"

### ISSUE THREAD

**Issue by AIPTU** [thebigcrafter/oh-my-pmmp#5]
https://crash.pmmp.io/view/7020403

**Comment by MintoD3v** [comment]
You can fix this error by restarting your server.  The version to fix this bug will be released soon.

**Comment by DavidGlitch04** [comment]
The bug has been fixed in commit [[b275fea](https://github.com/thebigcrafter/oh-my-pmmp/commit/b275fea2b08d19263787748e8a872647a727040b)]
